// Mocks generated by Mockito 5.4.4 from annotations
// in radiance_b2b_professional/test/presentation/widgets/admin_dashboard_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:radiance_b2b_professional/core/error/failures.dart' as _i5;
import 'package:radiance_b2b_professional/features/admin/data/repositories/admin_metrics_repository.dart'
    as _i3;
import 'package:radiance_b2b_professional/features/admin/domain/entities/admin_metrics_stats.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminMetricsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminMetricsRepository extends _i1.Mock
    implements _i3.AdminMetricsRepository {
  MockAdminMetricsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SystemMetrics>> getSystemMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSystemMetrics,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.SystemMetrics>>.value(
                _FakeEither_0<_i5.Failure, _i6.SystemMetrics>(
          this,
          Invocation.method(
            #getSystemMetrics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SystemMetrics>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RevenueMetrics>> getRevenueMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueMetrics,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.RevenueMetrics>>.value(
                _FakeEither_0<_i5.Failure, _i6.RevenueMetrics>(
          this,
          Invocation.method(
            #getRevenueMetrics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.RevenueMetrics>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserGrowthMetrics>>
      getUserGrowthMetrics() => (super.noSuchMethod(
            Invocation.method(
              #getUserGrowthMetrics,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.UserGrowthMetrics>>.value(
                _FakeEither_0<_i5.Failure, _i6.UserGrowthMetrics>(
              this,
              Invocation.method(
                #getUserGrowthMetrics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserGrowthMetrics>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TierDistribution>>
      getTierDistribution() => (super.noSuchMethod(
            Invocation.method(
              #getTierDistribution,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.TierDistribution>>.value(
                    _FakeEither_0<_i5.Failure, _i6.TierDistribution>(
              this,
              Invocation.method(
                #getTierDistribution,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TierDistribution>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UsageMetrics>> getUsageMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsageMetrics,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.UsageMetrics>>.value(
                _FakeEither_0<_i5.Failure, _i6.UsageMetrics>(
          this,
          Invocation.method(
            #getUsageMetrics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UsageMetrics>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SystemHealthMetrics>>
      getSystemHealthMetrics() => (super.noSuchMethod(
            Invocation.method(
              #getSystemHealthMetrics,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i6.SystemHealthMetrics>>.value(
                _FakeEither_0<_i5.Failure, _i6.SystemHealthMetrics>(
              this,
              Invocation.method(
                #getSystemHealthMetrics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.SystemHealthMetrics>>);
}
