// Mocks generated by Mockito 5.4.4 from annotations
// in radiance_b2b_professional/test/presentation/widgets/admin_audit_logs_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:radiance_b2b_professional/core/error/failures.dart' as _i5;
import 'package:radiance_b2b_professional/features/admin/data/repositories/admin_audit_repository.dart'
    as _i3;
import 'package:radiance_b2b_professional/features/admin/domain/entities/admin_audit_log.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminAuditRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminAuditRepository extends _i1.Mock
    implements _i3.AdminAuditRepository {
  MockAdminAuditRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminAuditLog>>> getAuditLogs({
    _i6.AuditLogFilters? filters,
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditLogs,
          [],
          {
            #filters: filters,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminAuditLog>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.AdminAuditLog>>(
          this,
          Invocation.method(
            #getAuditLogs,
            [],
            {
              #filters: filters,
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminAuditLog>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AdminAuditLog>> getAuditLogById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditLogById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.AdminAuditLog>>.value(
                _FakeEither_0<_i5.Failure, _i6.AdminAuditLog>(
          this,
          Invocation.method(
            #getAuditLogById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AdminAuditLog>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> createAuditLog({
    required String? action,
    required _i6.AuditLogCategory? category,
    String? userId,
    String? userName,
    String? targetId,
    String? targetType,
    String? targetName,
    Map<String, dynamic>? metadata,
    String? ipAddress,
    String? userAgent,
    _i6.AuditLogSeverity? severity = _i6.AuditLogSeverity.info,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAuditLog,
          [],
          {
            #action: action,
            #category: category,
            #userId: userId,
            #userName: userName,
            #targetId: targetId,
            #targetType: targetType,
            #targetName: targetName,
            #metadata: metadata,
            #ipAddress: ipAddress,
            #userAgent: userAgent,
            #severity: severity,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #createAuditLog,
            [],
            {
              #action: action,
              #category: category,
              #userId: userId,
              #userName: userName,
              #targetId: targetId,
              #targetType: targetType,
              #targetName: targetName,
              #metadata: metadata,
              #ipAddress: ipAddress,
              #userAgent: userAgent,
              #severity: severity,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuditLogStats>> getAuditLogStats({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditLogStats,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.AuditLogStats>>.value(
                _FakeEither_0<_i5.Failure, _i6.AuditLogStats>(
          this,
          Invocation.method(
            #getAuditLogStats,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuditLogStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> exportToCSV({
    _i6.AuditLogFilters? filters,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToCSV,
          [],
          {
            #filters: filters,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #exportToCSV,
            [],
            {
              #filters: filters,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> deleteOldLogs(
          DateTime? beforeDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldLogs,
          [beforeDate],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #deleteOldLogs,
            [beforeDate],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> countLogs(
          {_i6.AuditLogFilters? filters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #countLogs,
          [],
          {#filters: filters},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #countLogs,
            [],
            {#filters: filters},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);
}
