// Mocks generated by Mockito 5.4.4 from annotations
// in radiance_b2b_professional/test/presentation/widgets/admin_users_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:radiance_b2b_professional/core/error/failures.dart' as _i5;
import 'package:radiance_b2b_professional/features/admin/data/repositories/admin_user_repository.dart'
    as _i3;
import 'package:radiance_b2b_professional/features/admin/domain/entities/admin_user_stats.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminUserRepository extends _i1.Mock
    implements _i3.AdminUserRepository {
  MockAdminUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminUserStats>>> getAllUsers(
          _i6.UserFilters? filters) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [filters],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminUserStats>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.AdminUserStats>>(
          this,
          Invocation.method(
            #getAllUsers,
            [filters],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminUserStats>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AdminUserStats>> getUserDetails(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetails,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.AdminUserStats>>.value(
                _FakeEither_0<_i5.Failure, _i6.AdminUserStats>(
          this,
          Invocation.method(
            #getUserDetails,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AdminUserStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> disableUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #disableUser,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #disableUser,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> enableUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableUser,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #enableUser,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> resetPassword(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #resetPassword,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserActivityLog>>>
      getUserActivityLogs(
    String? userId, {
    int? days = 30,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getUserActivityLogs,
              [userId],
              {#days: days},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.UserActivityLog>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.UserActivityLog>>(
              this,
              Invocation.method(
                #getUserActivityLogs,
                [userId],
                {#days: days},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.UserActivityLog>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getSystemUserStats() => (super.noSuchMethod(
            Invocation.method(
              #getSystemUserStats,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getSystemUserStats,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
