// Mocks generated by Mockito 5.4.4 from annotations
// in radiance_b2b_professional/test/presentation/widgets/admin_subscriptions_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:radiance_b2b_professional/core/error/failures.dart' as _i5;
import 'package:radiance_b2b_professional/features/admin/data/repositories/admin_subscription_repository.dart'
    as _i3;
import 'package:radiance_b2b_professional/features/admin/domain/entities/admin_subscription_stats.dart'
    as _i6;
import 'package:radiance_b2b_professional/features/multi_tenant/domain/entities/subscription.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminSubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminSubscriptionRepository extends _i1.Mock
    implements _i3.AdminSubscriptionRepository {
  MockAdminSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminSubscriptionStats>>>
      getAllSubscriptions(_i6.SubscriptionFilters? filters) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAllSubscriptions,
              [filters],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i6.AdminSubscriptionStats>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.AdminSubscriptionStats>>(
              this,
              Invocation.method(
                #getAllSubscriptions,
                [filters],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.AdminSubscriptionStats>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AdminSubscriptionStats>>
      getSubscriptionDetails(String? subscriptionId) => (super.noSuchMethod(
            Invocation.method(
              #getSubscriptionDetails,
              [subscriptionId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i6.AdminSubscriptionStats>>.value(
                _FakeEither_0<_i5.Failure, _i6.AdminSubscriptionStats>(
              this,
              Invocation.method(
                #getSubscriptionDetails,
                [subscriptionId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AdminSubscriptionStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateSubscriptionTier(
    String? subscriptionId,
    _i7.SubscriptionTier? newTier,
    String? adminUserId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSubscriptionTier,
          [
            subscriptionId,
            newTier,
            adminUserId,
            reason,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateSubscriptionTier,
            [
              subscriptionId,
              newTier,
              adminUserId,
              reason,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelSubscription(
    String? subscriptionId,
    String? adminUserId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSubscription,
          [
            subscriptionId,
            adminUserId,
            reason,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #cancelSubscription,
            [
              subscriptionId,
              adminUserId,
              reason,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> reactivateSubscription(
    String? subscriptionId,
    String? adminUserId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactivateSubscription,
          [
            subscriptionId,
            adminUserId,
            reason,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #reactivateSubscription,
            [
              subscriptionId,
              adminUserId,
              reason,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> suspendSubscription(
    String? subscriptionId,
    String? adminUserId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #suspendSubscription,
          [
            subscriptionId,
            adminUserId,
            reason,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #suspendSubscription,
            [
              subscriptionId,
              adminUserId,
              reason,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> processRefund(
    String? paymentId,
    String? adminUserId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRefund,
          [
            paymentId,
            adminUserId,
            reason,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #processRefund,
            [
              paymentId,
              adminUserId,
              reason,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getSystemSubscriptionStats() => (super.noSuchMethod(
            Invocation.method(
              #getSystemSubscriptionStats,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getSystemSubscriptionStats,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
