// Mocks generated by Mockito 5.4.4 from annotations
// in radiance_b2b_professional/test/presentation/providers/admin_company_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:radiance_b2b_professional/core/error/failures.dart' as _i5;
import 'package:radiance_b2b_professional/features/admin/data/repositories/admin_company_repository.dart'
    as _i3;
import 'package:radiance_b2b_professional/features/admin/domain/entities/admin_company_stats.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminCompanyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminCompanyRepository extends _i1.Mock
    implements _i3.AdminCompanyRepository {
  MockAdminCompanyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.AdminCompanyStats>>> getAllCompanies(
          {_i6.CompanyFilters? filters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCompanies,
          [],
          {#filters: filters},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.AdminCompanyStats>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.AdminCompanyStats>>(
          this,
          Invocation.method(
            #getAllCompanies,
            [],
            {#filters: filters},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.AdminCompanyStats>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AdminCompanyStats>> getCompanyDetails(
          String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompanyDetails,
          [companyId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.AdminCompanyStats>>.value(
                _FakeEither_0<_i5.Failure, _i6.AdminCompanyStats>(
          this,
          Invocation.method(
            #getCompanyDetails,
            [companyId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AdminCompanyStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> suspendCompany(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #suspendCompany,
          [companyId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #suspendCompany,
            [companyId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> activateCompany(
          String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #activateCompany,
          [companyId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #activateCompany,
            [companyId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteCompany(String? companyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCompany,
          [companyId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteCompany,
            [companyId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getSystemStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSystemStats,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getSystemStats,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
